AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for DynamoDB Table"

Parameters:
  DynamoAttribute:
    Type: String
    Description: "DynamoDB Attribute Type"
  DynamoName:
    Type: String
    Description: "DynamoDB Table Name"

Resources:
  myDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: !Ref DynamoAttribute
          AttributeType: S
      KeySchema: 
        - AttributeName: !Ref DynamoAttribute
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification: 
        SSEEnabled: true
      TableName: !Ref DynamoName

Outputs:
  DynamoName:
    Description: "DynamoDB Table Name"
    Value: !Ref myDynamoDB
    Export:
      Name: DynamoName
